name: Pylint CI

on:
  pull_request:
    branches:
      - main  # Or your default branch
  push:
    branches:
      - main  # Or your default branch

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    <b>
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.1'  # Specify the Python version you're using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Or use any method to install your dependencies

    - name: Run Pylint
      run: |
        pylint leetcode  # Run pylint on all Python files in the repo
