name: Python Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint with Pylint
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13.1  # Specify the Python version you want

    # Step 3: Install dependencies
    - name: Install dependencies for linting
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Or use any method to install your dependencies

    # Step 4: Run pylint
    - name: Run pylint
      run: |
        pylint --rcfile=.pylintrc leetcode/  # Run pylint on all Python files in the repo

  tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: lint  # Ensures linting runs before testing

    steps:
    # Step 4: Run unit tests
    - name: Run unit tests
      run: |
        python -m unittest
